package com.trading.kalyani.KTManager.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

/**
 * Entity to store Trade Setup recommendations generated by CandlePredictionService.
 * Contains entry, target, stop-loss levels and option trading suggestions.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@Table(name = "trade_setup")
public class TradeSetupEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "trade_setup_seq")
    @SequenceGenerator(name = "trade_setup_seq", sequenceName = "trade_setup_seq", allocationSize = 1)
    private Long id;

    // Basic trade info
    @Column(name = "instrument_token")
    private Long instrumentToken;

    @Column(name = "trade_direction")
    private String tradeDirection;  // BUY, SELL, NONE

    @Column(name = "setup_type")
    private String setupType;  // ORDER_BLOCK, CHANNEL_BOUNCE, FIB_RETRACEMENT, CONFLUENCE

    @Column(name = "confidence")
    private Double confidence;  // 0-100 confidence score

    // Entry details
    @Column(name = "entry_price")
    private Double entryPrice;

    @Column(name = "entry_type")
    private String entryType;  // LIMIT, MARKET, STOP

    @Column(name = "entry_reason", length = 500)
    private String entryReason;

    // Target details
    @Column(name = "target1")
    private Double target1;  // First target (conservative)

    @Column(name = "target2")
    private Double target2;  // Second target (moderate)

    @Column(name = "target3")
    private Double target3;  // Third target (aggressive)

    @Column(name = "target_reason", length = 500)
    private String targetReason;

    // Stop-loss details
    @Column(name = "stop_loss")
    private Double stopLoss;

    @Column(name = "trailing_stop_distance")
    private Double trailingStopDistance;

    @Column(name = "stop_loss_reason", length = 500)
    private String stopLossReason;

    // Risk-Reward analysis
    @Column(name = "risk_points")
    private Double riskPoints;

    @Column(name = "reward_points1")
    private Double rewardPoints1;

    @Column(name = "risk_reward_ratio1")
    private Double riskRewardRatio1;

    @Column(name = "risk_reward_ratio2")
    private Double riskRewardRatio2;

    // Option trading specific
    @Column(name = "suggested_option_type")
    private String suggestedOptionType;  // CE, PE

    @Column(name = "suggested_strike")
    private Integer suggestedStrike;

    @Column(name = "option_strategy")
    private String optionStrategy;  // BUY_CE, BUY_PE, SELL_CE, SELL_PE

    // Market context at setup time
    @Column(name = "current_price")
    private Double currentPrice;

    @Column(name = "market_trend")
    private String marketTrend;  // BULLISH, BEARISH, NEUTRAL

    @Column(name = "smc_bias")
    private String smcBias;  // Smart Money Concepts bias

    @Column(name = "smc_confidence")
    private Double smcConfidence;

    @Column(name = "channel_type")
    private String channelType;  // ASCENDING, DESCENDING, HORIZONTAL

    @Column(name = "nearest_fib_level")
    private String nearestFibLevel;

    @Column(name = "pcr_value")
    private Double pcrValue;

    @Column(name = "max_pain_strike")
    private Integer maxPainStrike;

    // Validity and tracking
    @Column(name = "created_at")
    private LocalDateTime createdAt;

    @Column(name = "valid_until")
    private LocalDateTime validUntil;

    @Column(name = "is_valid")
    private Boolean isValid;

    @Column(name = "invalid_reason", length = 500)
    private String invalidReason;

    // Outcome tracking (to be updated later)
    @Column(name = "is_executed")
    private Boolean isExecuted = false;

    @Column(name = "execution_price")
    private Double executionPrice;

    @Column(name = "execution_time")
    private LocalDateTime executionTime;

    @Column(name = "is_closed")
    private Boolean isClosed = false;

    @Column(name = "exit_price")
    private Double exitPrice;

    @Column(name = "exit_time")
    private LocalDateTime exitTime;

    @Column(name = "exit_reason")
    private String exitReason;  // TARGET1_HIT, TARGET2_HIT, TARGET3_HIT, STOPLOSS_HIT, MANUAL, EXPIRED

    @Column(name = "profit_loss")
    private Double profitLoss;

    @Column(name = "profit_loss_percent")
    private Double profitLossPercent;
}

